name: Build and Test
env:
  DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Unit Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Swift packages
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: xcodebuild build-for-testing -project Wishlist.xcodeproj -scheme Wishlist -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.2'

      - name: Test
        run: xcodebuild test-without-building -project Wishlist.xcodeproj -scheme Wishlist -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.2'
